
version: '3.3'
#services describe the containers that will start
services: 
    # api is the container name for our Go API
    api:
        # It will look for a dockerfile in the project root and build it
        build: "."
        # Exposes the port 5000 from a container and binds it to a random port
        ports:
            - "8080:8080"
        # If the container goes down, it will restart
        restart: "always"
        # Connects the API to a common api.network bridge
        networks: 
            - "api.network"
# declares network used to connect all the apps
networks: 
    api.network: